PE-491 Run script to identify likely bank duplicates
bank-green/bankgreen-django pull request #138
Opened 2023-10-09 19:12 UTC by ahmedlamidi

2023-10-10 09:30 UTC, RogerTangos commented on brand/admin.py
> +from django_object_actions import DjangoObjectActions
django_object_actions needs to be added to `requirements.txt`

2023-10-10 09:41 UTC, RogerTangos requested changes
I'm not seeing duplicates appear although the `suggested_duplicates` dictionary is populated

<img width="595" alt="Screenshot 2023-10-10 at 11 40 00" src="https://github.com/bank-green/bankgreen-django/assets/1609475/0f1a05a7-f378-485a-a727-5ac0dec05868">

2023-10-10 09:41 UTC, RogerTangos commented on brand/admin.py
> +        return render(request,
`render` is not imported

2023-10-10 09:41 UTC, RogerTangos commented on brand/admin.py
> +from django_object_actions import DjangoObjectActions
I'm glad the library is well supported but it seems a bit unnecedssary to use django_object_actions here. Is there a way to do this without introducing a new dependency?

2023-10-10 14:13 UTC, ahmedlamidi commented
It should be working now, It was the html page that was not the same as the one running on my local system.

2023-10-11 16:50 UTC, RogerTangos commented
On the HTML page,

- The original brand will also need to be linked to ensure they're not the same.
- It should just display the brand name.
- If there are duplicates it should only suggest one.

I think that a pass through the dictionary would fix the last two points.

<img width="146" alt="Screenshot 2023-10-11 at 18 49 59" src="https://github.com/bank-green/bankgreen-django/assets/1609475/a7de9065-1fdd-41a4-9729-4c1db7815f39">

2023-10-19 13:54 UTC, closed without merging