Harmeetkaur
bank-green/bankgreen-django pull request #188
Opened 2024-10-25 14:13 UTC by Harmeetkaur13

Fixed issue #ticket_number 307: Added duplicate brand tag check with error message

2024-10-29 12:43 UTC, RogerTangos commented on brand/admin.py
> +            Brand.objects.filter(tag=obj.tag).exists() and not change
@Harmeetkaur13 - this is a picky thing, but you probably want to test for `not change` before testing for `.exists()`. The reason is that `.exists()` will have to make a database query whereas change is arelady stored in memory.

2024-10-29 18:10 UTC, nikita-pardeshi-github requested changes
Hi @Harmeetkaur13 This change does not work. User still get's 500 error. Basically, we need to raise validation error when user try to save the model with duplicate tag. So we want to add validation error for tag. You can update validation_tag method in Brand model like below. 

````
def validate_tag(value):
    """This is the function that is used to validate the TAG"""
    if re.match("^[A-Za-z0-9_-]*$", str(value)):
        if Brand.objects.filter(tag=value).exists():
            raise ValidationError(
                f"A brand with tag '{value}' already exists. Please edit that brand instead."
            )
        else:
            return value          
    else:
        raise ValidationError(
            "Tag can contain only alpha-numeric characters, underscores and dashes"
        )
````

2024-10-31 10:23 UTC, RogerTangos commented
Hey @Harmeetkaur13 - this is better, but you've got to run tests before pushing. In this case, it seems like the tests will need to be updated

2024-10-31 10:27 UTC, RogerTangos requested changes
Please run and update tests before opening the PR

2024-11-04 15:51 UTC, RogerTangos approved these changes
self approving here. I've tested

2024-11-04 16:16 UTC, merged